#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

#session=${1:-bspwm}

#case $session in
#    2bwm)
#        echo "2bwm started"
#        tint2 &
#        exec bspwm
#        ;;
#    xfce4)
#        echo "xfce4 started"
#        ;;
#    bspwm)
#        echo "bspwm started"
#        ;;
#    *)
#        echo $session
#        ;;
#esac

exec openbox-session
